"""add_ledger_entries_and_surge_multiplier

Revision ID: 45cfdae590c2
Revises: e2a36512f543
Create Date: 2026-09-22 10:37:25.032105

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45cfdae590c2'
down_revision: str | Sequence[str] | None = 'e2a36512f543'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('CUSTOMER', 'RESTAURANT', 'PLATFORM', name='ledgeraccounttype'), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='ledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_type'), 'ledger_entries', ['account_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_order_id'), 'ledger_entries', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('surge_multiplier', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'surge_multiplier')
    op.drop_index(op.f('ix_ledger_entries_order_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_type'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
