"""initial_migration

Revision ID: e2a36512f543
Revises: 
Create Date: 2026-09-22 10:21:49.220871

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2a36512f543'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_assignments', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('driver_profiles', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('5.0'))
    op.add_column('order_items', sa.Column('name_snapshot', sa.String(length=150), nullable=False))
    op.add_column('order_items', sa.Column('name_snapshot', sa.String(length=150), nullable=False, server_default='Món ăn'))
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_restaurants_owner_id'), 'restaurants', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_owner_id'), table_name='restaurants')
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_column('order_items', 'name_snapshot')
    op.alter_column('driver_profiles', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('5.0'))
    op.drop_column('delivery_assignments', 'delivered_at')
    # ### end Alembic commands ###
